#! /bin/sh
# Requires `uv`.

python_target_version=3.11
python_target_version_ruff=py$(echo "$python_target_version" | sed 's|\.||')

exit_status=0

uv tool run ruff format \
    --no-cache \
    --target-version "$python_target_version_ruff" \
    "$@" \
    ;
exit_status=$((exit_status + $?))

uv tool run ruff check \
    --fix \
    --ignore ANN,D,EXE003,S101,S310,S603,S607,T201,PT \
    --no-cache \
    --select ALL \
    --target-version "$python_target_version_ruff" \
    --unsafe-fixes \
    "$@" \
    ;
exit_status=$((exit_status + $?))

uv tool run pyright \
    --pythonversion "$python_target_version" \
    "$@" \
    ;
exit_status=$((exit_status + $?))

exit "$exit_status"
