name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: 'Disable `autocrlf` in Git'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Download busybox-w32
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri https://dbohdan.com/dist/busybox-w32-frp-5301-gda71f7c57.7z -OutFile busybox.7z
          7z x -obusybox busybox.7z
          New-Item -Path busybox.exe -ItemType SymbolicLink -Value busybox\busybox.exe

          if (
            (Get-FileHash -Algorithm SHA256 busybox.exe).Hash -ne "DD6B2FC4D4809FF39F0E738C0DCB85624187ABF3E3239043BDD4E64BB4BA8EC3"
          ) {
            throw "Wrong checksum: busybox.exe"
          }

      - name: Test
        if: matrix.os != 'windows-latest'
        run: |
          make PYTHON_VERSION=${{ matrix.python-version }} test

      - name: Test with busybox-w32
        if: matrix.os == 'windows-latest'
        run: |
          $env:PYCHECK_COMMAND='busybox sh pycheck'
          .\busybox make PYTHON_VERSION=${{ matrix.python-version }} test
